apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicacy
spec:
  selector:
    matchLabels:
      run: duplicacy
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
          run: duplicacy
    spec:
      hostname: duplicacy-pod
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
        - name: promtail-config
          configMap:
            name: sidecar-promtail
        - name: sidecar-promtail-logs
          emptyDir:
            medium: Memory 
      containers:
        - name: promtail-sidecar
          image: grafana/promtail:2.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/config.yml"
            - '--client.external-labels=run=$(POD_RUN),namespace=$(POD_NAMESPACE),pod=$(POD_NAME)' 
          env:
            - name: POD_RUN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['run']
            - name: POD_NAMESPACE 
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: sidecar-promtail-logs
              mountPath: /sidecar-logs
            - mountPath: /etc/promtail
              name: promtail-config
        - name: duplicacy
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "5Gi"
          env:
            - name: "TZ"
              value: "Europe/Berlin"
            - name: "DUPLICACY_WEB_VERSION"
              value: "Latest"
            - name: "DWE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: duplicacy
                  key: password
            - name: "MACHINE_ID"
              valueFrom:
                secretKeyRef:
                  name: duplicacy
                  key: machine-id
          image: saspus/duplicacy-web:mini 
          ports:
            - containerPort: 3875
              name: duplicacy
              protocol: TCP
          volumeMounts:
            - mountPath: "/logs"
              name: nfs
              subPath: ".docker/config/duplicacy/logs"
            - mountPath: "/config"
              name: nfs
              subPath: ".docker/config/duplicacy"
            - mountPath: "/cache"
              name: nfs
              subPath: ".docker/cache/duplicacy"
            - name: nfs
              mountPath: "/storage"
---

apiVersion: v1
kind: Service
metadata:
  name: duplicacy
  labels:
    run: duplicacy
spec:
  ports:
  - port: 3875
    protocol: TCP
  selector:
    run: duplicacy

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: duplicacy
spec:
  rules:
  - host: duplicacy.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: duplicacy
          servicePort: 3875
  - host: duplicacy.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: duplicacy
          servicePort: 3875

