# ingress only, loki-grafana from the loki-stack helmchart does the rest.
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: loki
spec:
  rules:
  - host: grafana.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: loki-grafana
          servicePort: 80

