apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      run: jackett
  replicas: 1 
  template:
    metadata:
      labels:
        run: jackett
    spec:
      volumes:
        - name: nfs-media
          persistentVolumeClaim:
            claimName: media
        - name: nfs-config
          persistentVolumeClaim:
            claimName: app-configs
      containers:
      - name: jackett
        image: linuxserver/jackett
        ports:
          - containerPort: 9117
        env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: "Europe/Berlin"
        volumeMounts:
          - name: nfs-config
            mountPath: "/config"
            subPath: "jackett"
          - name: nfs-media
            mountPath: "/data"
            subPath: "Downloads"
          - name: nfs-media
            mountPath: "/downloads"
            subPath: "Downloads"

---

apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    run: jackett
spec:
  ports:
  - port: 9117
    protocol: TCP
  selector:
    run: jackett

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
spec:
  rules:
  - host: jackett.cluster.vert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett
            port:
              number: 9117

