apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1 
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      volumes:
        - name: ramdisk
          emptyDir:
            sizeLimit: 500M
            medium: Memory

        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
      - name: mariadb
        image: linuxserver/mariadb
        resources:
          requests:
            memory: "512Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "2000m"
        ports:
          - containerPort: 3306
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -ec
              - |
                password_aux="${MYSQL_ROOT_PASSWORD:-}"
                mysqladmin status -uroot -p"${password_aux}"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: "Europe/Berlin"
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: rootpass
          - name: MYSQL_USER
            value: "nextcloud"
          - name: MYSQL_DATABASE
            value: "nextcloud"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb
                key: nextcloudpass
        volumeMounts:
          - name: nfs
            mountPath: "/config"
            subPath: ".docker/config/mariadb"
          - name: ramdisk
            mountPath: "/ramdisk"
---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: LoadBalancer
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
