---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock
  labels:
    role: service-config
    run: minecraft
data:
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  # Remove # from in front of line if changing from default values.
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  GAMEMODE: "creative" # Options: survival, creative, adventure
  #DIFFICULTY: "easy" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  LEVEL_NAME: "vertesi_minecraft_world"
  #LEVEL_SEED: "33480944"
  SERVER_NAME: "vertesi_minecraft_server"
  #SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  #ALLOW_CHEATS: "false" # Options: true, false
  #MAX_PLAYERS: "10"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  WHITE_LIST: "true" # If enabled, need to provide a allowlist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"
  #OPS: "2535426888531412"
  #MEMBERS: "2535405923965293"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-allowlist
  labels:
    role: service-config
    run: minecraft
data:
  allowlist.json: |
    [{"ignoresPlayerLimit":false,"name":"booboobutt2015","xuid":"2535405923965293"},{"ignoresPlayerLimit":false,"name":"odhugemanate","xuid":"2535426888531412"}]

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    run: minecraft
  name: minecraft
spec:
  # never more than 1 since minecraft is not horizontally scalable
  replicas: 1
  serviceName: minecraft
  selector:
    matchLabels:
      run: minecraft
  template:
    metadata:
      labels:
        run: minecraft
    spec:
      volumes:
      - name: allowlist
        configMap:
           name: minecraft-allowlist
           items:
             - key: allowlist.json
               path: allowlist.json
      containers:
        - name: main
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-bedrock
          volumeMounts:
            - mountPath: /data
              name: data
            - name: allowlist
              mountPath: /data/allowlist.json
              subPath: allowlist.json
          ports:
            - containerPort: 19132
              protocol: UDP
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
            initialDelaySeconds: 30
          livenessProbe: *probe
          tty: true
          stdin: true
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: LoadBalancer
  selector:
    run: minecraft
  ports:
    - port: 19132
      protocol: UDP

