apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: nextcloud
  labels:
    run: nextcloud
spec:
  selector:
    matchLabels:
      run: nextcloud
  replicas: 1 
  serviceName: nextcloud
  volumeClaimTemplates:
    - metadata:
        name: nextcloud-www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        run: nextcloud
    spec:
      volumes:
        - name: nfs-nextcloud
          persistentVolumeClaim:
            claimName: nextcloud
        - name: nfs-media
          persistentVolumeClaim:
            claimName: media
        - name: nfs-config
          persistentVolumeClaim:
            claimName: app-configs
        - name: promtail-config
          configMap:
            name: sidecar-promtail
        - name: nextcloud-logs
          emptyDir: {}
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: nextcloud
          image: lscr.io/linuxserver/nextcloud:26.0.0-ls238
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "1000m" 
              memory: "2Gi"
            limits:
              cpu: "2000m" 
              memory: "4Gi"
          startupProbe:
            exec:
              command:
                - pgrep
                - nginx
            initialDelaySeconds: 60
            periodSeconds: 10 
            timeoutSeconds: 10
            failureThreshold: 120 
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - pgrep
                - nginx
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 10 
            successThreshold: 1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 80
              name: nextcloud
              protocol: TCP
          volumeMounts:
            - name: nfs-nextcloud
              mountPath: "/data"
            - name: nfs-config
              mountPath: "/custom-cont-init.d"
              subPath: "nextcloud/server-config/custom-init"
            - name: nfs-media
              mountPath: "/media"
            - name: nextcloud-www
              mountPath: "/www"
            - name: nfs-config
              mountPath: "/www/nextcloud/config"
              subPath: "nextcloud/nextcloud-config"
            - name: nfs-config
              mountPath: "/config"
              subPath: "nextcloud/server-config"
            - name: nextcloud-logs
              mountPath: "/config/log"
        - name: nextcloud-promtail
          image: grafana/promtail:2.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/config.yml"
            - '--client.external-labels=run=$(POD_RUN),namespace=$(POD_NAMESPACE),pod=$(POD_NAME)' 
          env:
            - name: POD_RUN
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['run']
            - name: POD_NAMESPACE 
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nextcloud-logs
              mountPath: /sidecar-logs
            - mountPath: /etc/promtail
              name: promtail-config
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    run: nextcloud
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nextcloud

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-max-age: "15552000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: nextcloud.cluster.vert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80
  - host: nextcloud.vert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80
  - host: germany.vertesi.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud
            port:
              number: 80
  tls:
  - hosts:
    - germany.vertesi.com
    secretName: germany-vertesi-com-tls

