apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nextcloud
  labels:
    run: nextcloud
spec:
  selector:
    matchLabels:
      run: nextcloud
  replicas: 2 
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        run: nextcloud
    spec:
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: nextcloud
          image: ghcr.io/ohthehugemanatee/docker-nextcloud:multiarch
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "2000m" 
          startupProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 15
            failureThreshold: 10 
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /status.php
              port: 80
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6 
            successThreshold: 1
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - containerPort: 80
              name: nextcloud
              protocol: TCP
          volumeMounts:
            - name: nfs
              mountPath: "/data"
              subPath: "nextcloud"
            - name: nfs
              mountPath: "/www"
              subPath: ".docker/config/nextcloud-www"
            - name: nfs
              mountPath: "/config"
              subPath: ".docker/config/nextcloud"
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    run: nextcloud
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nextcloud

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    traefik.frontend.priority: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-max-age: "15552000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: nextcloud.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  - host: nextcloud.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  - host: germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  tls:
  - hosts:
    - germany.vertesi.com
    secretName: germany-vertesi-com-tls

