apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
spec:
  selector:
    matchLabels:
      run: nzbget
  replicas: 1 
  template:
    metadata:
      labels:
        run: nzbget
    spec:
      volumes:
        - name: nfs-media
          persistentVolumeClaim:
            claimName: media
        - name: nfs-config
          persistentVolumeClaim:
            claimName: app-configs
      containers:
      - name: nzbget
        image: linuxserver/nzbget
        ports:
          - containerPort: 6789
        env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: "Europe/Berlin"
        volumeMounts:
          - name: nfs-config
            mountPath: "/config"
            subPath: "nzbget"
          - name: nfs-media
            mountPath: "/downloads"
            subPath: "Downloads"

---

apiVersion: v1
kind: Service
metadata:
  name: nzbget
  labels:
    run: nzbget
spec:
  ports:
  - port: 6789
    protocol: TCP
  selector:
    run: nzbget

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
spec:
  rules:
  - host: nzbget.cluster.vert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget
            port:
              number: 6789
  - host: nzbget.vert
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nzbget
            port:
              number: 6789

