apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      run: plex
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: plex
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - until [ -f "/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.blobs.db" ]; do sleep 1; done; /init
          resources:
            requests:
              memory: "1024Mi"
              cpu: "2000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m" 
              gpu.intel.com/i915: 1
          ports:
            - containerPort: 32400
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: VERSION
              value: "public"
          volumeMounts:
            - mountPath: /config
              name: nfs
              subPath: ".docker/config/plex"
            - name: nfs
              mountPath: "/shared"
            - name: nfs
              mountPath: "/data/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/data/music"
              subPath: "media/Music"
            - name: nfs
              mountPath: "/music"
              subPath: "media/Music"
            - name: nfs
              mountPath: "/data/tv"
              subPath: "media/TV Shows"
            - name: nfs
              mountPath: "/tv"
              subPath: "media/TV Shows"
            - name: nfs
              mountPath: "/transcode"
              subPath: "media/.plex-transcode"

---

apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    run: plex
spec:
  ports:
  - port: 32400
    protocol: TCP
  selector:
    run: plex

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
  - host: plex.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
  - host: plex.germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
  - host: plex.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
---
apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  labels:
    run: plex-lb
spec:
  type: LoadBalancer
  selector:
    run: plex
  ports:
    - protocol: TCP
      port: 32400
