apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      nodeSelector:
        k3s.io/hostname: nextcloud
      volumes:
        - name: ramdisk
          emptyDir:
            sizeLimit: 1G 
            medium: Memory
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
        - emptyDir: {}
          name: plex-ramdisk-mount
      containers:
        - name: plex-config
          command:
            - sh
            - -c
            - |-
              dd if=/dev/zero of=/ramdisk/image.ext4 count=0 bs=1 seek=1G; \
              mkfs.ext4 /ramdisk/image.ext4; \
              mount /ramdisk/image.ext4 /mnt/plex-ramdisk-mount; \
              cp -fvpR /plex-config/* /mnt/plex-ramdisk-mount; \
              trap 'exit 0' 15; \
              while true; do \
              sleep 43200; \
              sync /mnt/plex-ramdisk-mount/*; \
              fsfreeze --freeze /mnt/plex-ramdisk-mount; \
              sleep 10; \
              rsync -a /mnt/plex-ramdisk-mount/ /plex-config/; \
              fsfreeze --unfreeze /mnt/plex-ramdisk-mount; \
              done;
          image: ubuntu
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: ramdisk
              mountPath: /ramdisk
            - name: nfs
              mountPath: /plex-config
              subPath: ".docker/config/plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases.backup"
            - mountPath: /mnt/plex-ramdisk-mount
              mountPropagation: Bidirectional
              name: plex-ramdisk-mount
        - name: plex
          image: linuxserver/plex
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - until [ -f "/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.blobs.db" ]; do sleep 1; done; /init
          resources:
            requests:
              memory: "2048Mi"
              cpu: "3000m"
            limits:
              memory: "2048Mi"
              cpu: "3000m" 
          ports:
            - containerPort: 32400
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: VERSION
              value: "public"
          volumeMounts:
            - mountPath: /config
              name: nfs
              subPath: ".docker/config/plex"
            - mountPath: "/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases"
              mountPropagation: HostToContainer
              name: plex-ramdisk-mount
            - name: nfs
              mountPath: "/shared"
            - name: nfs
              mountPath: "/data/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/data/music"
              subPath: "media/Music"
            - name: nfs
              mountPath: "/music"
              subPath: "media/Music"
            - name: nfs
              mountPath: "/data/tv"
              subPath: "media/TV Shows"
            - name: nfs
              mountPath: "/tv"
              subPath: "media/TV Shows"
            - name: nfs
              mountPath: "/transcode"
              subPath: "media/.plex-transcode"

---

apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  ports:
  - port: 32400
    protocol: TCP
  selector:
    app: plex

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
  - host: plex.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
  - host: plex.germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
  - host: plex.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: plex
          servicePort: 32400
---
apiVersion: v1
kind: Service
metadata:
  name: plex-lb
  labels:
    app: plex-lb
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
    - protocol: TCP
      port: 32400
