apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      run: radarr
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: radarr
    spec:
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
        - name: iscsivol
          iscsi:
             targetPortal: 192.168.1.50
             iqn: "iqn.2003-01.org.linux-scsi.warehouse:radarr"
             chapAuthDiscovery: false
             chapAuthSession: false
             lun: 0
             fsType: 'ext4'
             readOnly: false
      containers:
        - name: radarr
          image: linuxserver/radarr
          ports:
            - containerPort: 7878
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - mountPath: /config
              name: iscsivol
            - name: nfs
              mountPath: "/downloads"
              subPath: "media/Downloads"
            - name: nfs
              mountPath: "/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/data"
              subPath: "media/Downloads"

---

apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    run: radarr
spec:
  ports:
  - port: 7878
    protocol: TCP
  selector:
    run: radarr

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
spec:
  rules:
  - host: radarr.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878
  - host: radarr.germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878
  - host: radarr.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878

