apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      run: radarr
  replicas: 1 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: radarr
    spec:
      terminationGracePeriodSeconds: 300
      volumes:
        - name: ramdisk
          emptyDir: {}
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
        - emptyDir: {}
          name: radarr-ramdisk-mount
      containers:
        - name: radarr-config
          image: ghcr.io/ohthehugemanatee/sidecar-sync:multiarch
          imagePullPolicy: Always
          resources: {}
          env:
            - name: SIZE
              value: '1200M'
            - name: STORAGE
              value: /tmp/radarr-durable-storage
            - name: RAMDISK_MOUNTPOINT
              value: /mnt/radarr-active-storage
            - name: RAMDISK
              value: /tmp/radarr-ramdisk
          securityContext:
            privileged: true
          volumeMounts:
            - name: ramdisk
              mountPath: /tmp/radarr-ramdisk
            - name: nfs
              mountPath: /tmp/radarr-durable-storage
              subPath: ".docker/config/radarr"
            - name: radarr-ramdisk-mount
              mountPath: /mnt/radarr-active-storage
              mountPropagation: Bidirectional
        - name: radarr
          command:
            - sh
            - -c
            - until [ -f "/config/ready" ]; do sleep 1; done; /init
          image: linuxserver/radarr
          ports:
            - containerPort: 7878
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - mountPath: /config
              mountPropagation: HostToContainer
              name: radarr-ramdisk-mount
            - name: nfs
              mountPath: /radarr-config
              subPath: ".docker/config/radarr"
            - name: nfs
              mountPath: "/downloads"
              subPath: "media/Downloads"
            - name: nfs
              mountPath: "/movies"
              subPath: "media/Movies"
            - name: nfs
              mountPath: "/data"
              subPath: "media/Downloads"

---

apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    run: radarr
spec:
  ports:
  - port: 7878
    protocol: TCP
  selector:
    run: radarr

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: radarr
spec:
  rules:
  - host: radarr.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878
  - host: radarr.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: radarr
          servicePort: 7878

