apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      run: redis
  template:
    metadata:
      labels:
        run: redis
        name: redis
    spec:
      containers:
      - name: redis-server
        image: redis
        args: 
          - "--appendonly"
          - "no"
          - "--maxmemory"
          - "16mb"
          - "--maxmemory-policy"
          - "allkeys-lru"
          - "--save"
          - ""
        ports:
          - name: redis-server
            containerPort: 6379
        volumeMounts:
          - name: nfs
            subPath: ".docker/config/redis"
            mountPath: "/data"
        env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    run: redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
