apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: librephotos
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-claim
      containers:
      - name: backend
        image: reallibrephotos/librephotos:dev
        resources:
          requests:
            memory: "2700Mi"
            cpu: "2000m"
          limits:
            memory: "4000Mi"
            cpu: "4000m"
        env:
          - name: BACKEND_HOST
            value: backend
          - name: DB_BACKEND
            value: postgresql
          - name: DB_NAME
            value: librephotos
          - name: DB_HOST
            value: postgres
          - name: DB_PORT
            value: "5432"
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: "6379"
          - name: TIME_ZONE
            value: "Europe/Berlin"
          - name: DEBUG
            value: "1"
          - name: HEAVYWEIGHT_PROCESS
            value: "2"
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: admin-email
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: admin-username
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: admin-password
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: db-username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: db-password
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: secret-key
          - name: MAPBOX_API_KEY
            valueFrom:
              secretKeyRef:
                name: librephotos
                key: mapbox
        volumeMounts:
        - name: nfs
          mountPath: "/data"
          subPath: "nextcloud/ohthehugemantee/files/archive/Photos"
        - name: nfs
          mountPath: "/protected_media"
          subPath: ".docker/config/librephotos/protected_media"
        - name: nfs
          mountPath: "/logs"
          subPath: ".docker/config/librephotos/logs"
        - name: nfs
          mountPath: "/cache"
          subPath: ".docker/config/librephotos/cache"
        ports:
          - containerPort: 8001
            name: backend
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: librephotos
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: backend
  - name: http-8001
    port: 8001
    protocol: TCP
    targetPort: backend
  selector:
    run: backend
