apiVersion: v1
kind: PersistentVolume
metadata:
  name: librephotos-nfs
  namespace: librephotos
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: warehouse.vert
    path: "/mnt/storage"
    readOnly: false

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
  namespace: librephotos
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: ""
