apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: octoprint
  name: octoprint
  namespace: octoprint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: longhorn
