parent:
  claiming:
    enabled: true
    token: "token-here"
    rooms: "rooms-here"
  database:
    volumesize: 4Gi

child:
  claiming:
    enabled: true
    token: "token-here"
    rooms: "rooms-here"
  resources:
    limits:
      memory: 200Mi
  configs:
    netdata:
      data: |
        [global]
          update every = 5
        [db]
          mode = ram
        [health]
          enabled = no
        [ml]
          enabled = no

k8sState:
  enabled: false

ml:
  enabled: false

restarter:
  enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ""
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - netdata.k8s.local
    - netdata.cluster.vert

