image:
  tag: edge

parent:
  claiming:
    enabled: true
    token: "foo"
    rooms: "bar"
  database:
    volumesize: 4Gi

child:
  claiming:
    enabled: true
    token: "foo"
    rooms: "bar"
  resources:
    limits:
      memory: 200Mi
  configs:
    netdata:
      data: |
        [global]
          update every = 5
        [db]
          mode = ram
        [health]
          enabled = no
        [ml]
          enabled = no

k8sState:
  enabled: true

ml:
  enabled: false

restarter:
  enabled: true

ingress:
  enabled: false
