parent:
  claiming:
    enabled: true
    token: "token-here"
    rooms: "rooms-here"

child:
  claiming:
    enabled: true
    token: "token-here"
    rooms: "rooms-here"
  configs:
    netdata:
      data: |
        [global]
          memory mode = dbengine
          page cache size = 32
          dbengine multihost disk space = 256
          update every = 5
        [health]
          enabled = yes
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ""
    traefik.ingress.kubernetes.io/redirect-entry-point: https
  hosts:
    - netdata.k8s.local
    - netdata.cluster.vert

