apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: db-sync-checking-cron
spec:
  schedule: "0 */6 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - curl -k https://db-ynab-sync.cluster.vert/
          restartPolicy: Never
