apiVersion: batch/v1
kind: CronJob
metadata: 
  name: nextcloud-preview-generate
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: nfs
              persistentVolumeClaim:
                claimName: nfs-claim
          containers:
            - name: nextcloud
              image: lscr.io/linuxserver/nextcloud:latest
              command: ["/bin/sh", "-c"]
              args:
                - /init;
                  apk add --no-cache ffmpeg;
                  sudo -u abc /usr/bin/occ preview:pre-generate;
                  echo done;
              resources:
                requests:
                  memory: "2048Mi"
                  cpu: "1000m" 
                limits:
                  memory: "2048Mi"
                  cpu: "1000m" 
              env:
                - name: PUID
                  value: "1000"
                - name: PGID
                  value: "1000"
                - name: TZ
                  value: "Europe/Berlin"
              volumeMounts:
                - name: nfs
                  mountPath: "/data"
                  subPath: "nextcloud"
                - name: nfs
                  mountPath: "/custom-cont-init.d"
                  subPath: "nextcloud/custom-init"
                - name: nfs
                  mountPath: "/nfs"
                - name: nfs
                  mountPath: "/www"
                  subPath: ".docker/config/nextcloud-www"
                - name: nfs
                  mountPath: "/config"
                  subPath: ".docker/config/nextcloud"
