apiVersion: batch/v1
kind: Job
metadata: 
  name: nextcloud-update
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
        - name: nextcloud
          image: ghcr.io/linuxserver/nextcloud
          command: ["/bin/sh", "-c"]
          args:
            - /init;
              sudo -u abc php $NEXTCLOUD_PATH/updater/updater.phar;
              echo done;
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
          volumeMounts:
            - name: nfs
              mountPath: "/data"
              subPath: "nextcloud"
            - name: nfs
              mountPath: "/config"
              subPath: ".docker/config/nextcloud"
