global:
  domain: argocd.cluster.vert

server:
  insecure: true
  nodeSelector:
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

controller:
  nodeSelector:
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 512Mi

repoServer:
  nodeSelector:
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

redis:
  nodeSelector:
    kubernetes.io/arch: amd64
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

applicationSet:
  enabled: false

notifications:
  enabled: true
  nodeSelector:
    kubernetes.io/arch: amd64

dex:
  enabled: false
