apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: default
spec:
  nodeSelector:
    k3s.io/hostname: airbernetes
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

