deployment:
  image: quay.io/go-skynet/local-ai:latest
  env:
    REBUILD: "false"
replicaCount: 0
resources:
  limits:
    gpu.intel.com/i915: 1
    memory: 8Gi
models:
  forceDownload: false
  list:
    - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClass: "longhorn"

