FROM ghcr.io/linuxserver/nextcloud:amd64-latest
RUN curl https://raw.githubusercontent.com/ohthehugemanatee/docker-baseimage-alpine-nginx/ohthehugemanatee-patch-2/root/etc/cont-init.d/20-config -o /etc/cont-init.d/20-config
