---
- name: Show facts
  become: true
  hosts: all
  vars_files:
    - 'secrets.yaml'
  tasks:
    - name: Show variables and facts available on the system
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
