apiVersion: v1
kind: PersistentVolume
metadata:
  name: shoebox-configs
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: shoebox
    path: "/export/configs/config"
    readOnly: false

