apiVersion: v1
kind: PersistentVolume
metadata:
  name: shoebox-media
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  capacity:
    storage: 24Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: shoebox
    path: "/export/media"
    readOnly: false

