apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: nextcloud
spec:
  volumeName: shoebox-nextcloud
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 24Ti
  storageClassName: ""
