apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: app-configs
spec:
  volumeName: shoebox-configs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: ""
