apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      run: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        run: nextcloud
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
      containers:
        - name: nextcloud
          image: ghcr.io/linuxserver/nextcloud
          startupProbe:
            httpGet:
              path: /login
              port: 80
            failureThreshold: 40
            periodSeconds: 10 
          livenessProbe:
            httpGet:
              path: /login
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 3
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Berlin"
            - name: "OVERWRITEHOST"
              value: "nextcloud.cluster.vert"
          ports:
            - containerPort: 80
              name: nextcloud
              protocol: TCP
          volumeMounts:
            - name: nfs
              mountPath: "/data"
              subPath: "nextcloud"
            - name: nfs
              mountPath: "/config"
              subPath: ".docker/config/nextcloud"
---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  labels:
    run: nextcloud
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: nextcloud

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-dav
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /remote.php/dav/
    traefik.frontend.priority: "1"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-max-age: "15552000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
spec:
  rules:
  - host: germany.vertesi.com
    http:
      paths:
      - path: /.well-known/(card|cal)dav
        backend:
          serviceName: nextcloud
          servicePort: http
  tls:
  - hosts:
    - germany.vertesi.com
    secretName: germany-vertesi-com-tls
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud-dav
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /public.php?service=webfinger
    traefik.frontend.priority: "1"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-max-age: "15552000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
spec:
  rules:
  - host: germany.vertesi.com
    http:
      paths:
      - path: /.well-known/webfinger
        backend:
          serviceName: nextcloud
          servicePort: http
  tls:
  - hosts:
    - germany.vertesi.com
    secretName: germany-vertesi-com-tls
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    traefik.frontend.priority: "2"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/hsts-max-age: "15552000"
    ingress.kubernetes.io/hsts-include-subdomains: "true"
    ingress.kubernetes.io/hsts-preload: "true"
spec:
  rules:
  - host: nextcloud.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  - host: nextcloud.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  - host: germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
  tls:
  - hosts:
    - germany.vertesi.com
    secretName: germany-vertesi-com-tls

