apiVersion: v1
kind: Endpoints
metadata:
  name: plex
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 32400
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32400
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plex
spec:
  rules:
  - host: plex.vert
    http:
      paths:
      - backend:
          serviceName: plex
          servicePort: 80
        path: /
  - host: plex.cluster.vert
    http:
      paths:
      - backend:
          serviceName: plex
          servicePort: 80
        path: /
