apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  selector:
    matchLabels:
      run: sonarr
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
          run: sonarr
    spec:
      volumes:
        - name: ramdisk
          emptyDir:
            medium: Memory
            sizeLimit: 400M
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-claim
        - emptyDir: {}
          name: sonarr-ramdisk-mount
      containers:
        - name: sonarr-config
          command:
            - sh
            - -c
            - |-
              dd if=/dev/zero of=/ramdisk/image.ext4 count=0 bs=1 seek=400M; \
              mkfs.ext4 /ramdisk/image.ext4; \
              mount /ramdisk/image.ext4 /mnt/sonarr-ramdisk-mount; \
              cp -fvpR /sonarr-config/* /mnt/sonarr-ramdisk-mount; \
              while true; do \
              sleep 890; \
              sync /mnt/sonarr-ramdisk-mount/*.*; \
              fsfreeze --freeze /mnt/sonarr-ramdisk-mount; \
              sleep 10; \
              cp -fvp /mnt/sonarr-ramdisk-mount/*.* /sonarr-config/; \
              fsfreeze --unfreeze /mnt/sonarr-ramdisk-mount; \
              done;
          image: ubuntu
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - umount /mnt/sonarr-ramdisk-mount;
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - name: ramdisk
              mountPath: /ramdisk
            - name: nfs
              mountPath: /sonarr-config
              subPath: ".docker/config/sonarr"
            - mountPath: /mnt/sonarr-ramdisk-mount
              mountPropagation: Bidirectional
              name: sonarr-ramdisk-mount
        - name: sonarr
          command:
            - sh
            - -c
            - until [ -f "/config/config.xml" ]; do sleep 1; done; /init
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/sonarr
          ports:
            - containerPort: 8989
              name: sonarr
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              mountPropagation: HostToContainer
              name: sonarr-ramdisk-mount
            - name: nfs
              mountPath: "/downloads"
              subPath: "media/Downloads"
            - name: nfs
              mountPath: "/tv"
              subPath: "media/TV Shows"
---

apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    run: sonarr
spec:
  ports:
  - port: 8989
    protocol: TCP
  selector:
    run: sonarr

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sonarr
spec:
  rules:
  - host: sonarr.cluster.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarr
          servicePort: 8989
  - host: sonarr.vert
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarr
          servicePort: 8989
  - host: sonarr.germany.vertesi.com
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarr
          servicePort: 8989

