grafana:
  enabled: true
  persistence:
    enabled: true
  ingress:
    enabled: true
    hosts:
      - grafana.cluster.vert
  nodeSelector:
    # because some grafana plugins don't support arm64 yet.
    kubernetes.io/arch: amd64
prometheus:
  enabled: true
  server:
    persistentVolume:
      storageClass: "longhorn"
  alertmanager:
    persistentVolume:
      storageClass: "longhorn"
loki:
  persistence:
    enabled: false

