---
storageClass:
  isDefaultClass: "true"
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    dataEngine: v1
    dataLocality: disabled
    disableRevisionCounter: "true"
    fromBackup: ""
    fsType: ext4
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
    unmapMarkSnapChainRemoved: ignored

settings:
  backup-compression-method: gzip
  concurrent-automatic-engine-upgrade-per-node-limit: "5"
  default-data-locality: best-effort
  default-replica-count: "2"
  detach-manually-attached-volumes-when-cordoned: "true"
  disable-revision-counter: "true"
  node-down-pod-deletion-policy: delete-both-statefulset-and-deployment-pod
  node-drain-policy: allow-if-replica-is-stopped
  orphan-auto-deletion: "true"
  priority-class: longhorn-critical
  remove-snapshots-during-filesystem-trim: "true"
  replica-auto-balance: best-effort
  v2-data-engine-hugepage-limit: "1024"
