---
defaultSettings:
  backupCompressionMethod: gzip
  concurrentAutomaticEngineUpgradePerNodeLimit: 5
  defaultDataLocality: best-effort
  defaultReplicaCount: 2
  detachManuallyAttachedVolumesWhenCordoned: true
  disableRevisionCounter: true
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  nodeDrainPolicy: allow-if-replica-is-stopped
  orphanResourceAutoDeletion: replica-data
  priorityClass: longhorn-critical
  removeSnapshotsDuringFilesystemTrim: true
  replicaAutoBalance: best-effort

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack  # matches the Prometheus serviceMonitorSelector

persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  defaultFsType: ext4
  defaultDataLocality: disabled
  reclaimPolicy: Delete
  disableRevisionCounter: "true"
  unmapMarkSnapChainRemoved: ignored
  dataEngine: v1
  # Keeps StorageClass immutable.
  backupTargetName: ""

preUpgradeChecker:
  jobEnabled: true
  upgradeVersionCheck: true
