---
- name: Apply sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
    enabled: true
  when: ansible_virtualization_type != 'docker'

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
  when: ansible_virtualization_type != 'docker'

- name: Restart iscsid
  ansible.builtin.systemd:
    name: iscsid
    state: restarted
  when: ansible_virtualization_type != 'docker'

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_virtualization_type != 'docker'

- name: Restart k3s
  ansible.builtin.systemd:
    name: "{{ 'k3s-agent' if cluster_role == 'agent' else 'k3s' }}"
    state: restarted
  when: ansible_virtualization_type != 'docker'
  throttle: 1

- name: Restart zramswap
  ansible.builtin.systemd:
    name: zramswap
    state: restarted
    enabled: true
  when: ansible_virtualization_type != 'docker'
