apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: longhorn-ephemeral
parameters:
  dataLocality: strict-local
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "10"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
