apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: longhorn-ephemeral-fast
parameters:
  dataLocality: strict-local
  fromBackup: ""
  fsType: ext4
  numberOfReplicas: "1"
  staleReplicaTimeout: "10"
  diskSelector: "nvme"
  nodeSelector: "nvme"
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
