apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: unifi
  name: unifi-configs
spec:
  volumeName: unifi-configs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Ti
  storageClassName: ""
