apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-unknown.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: alloy
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 0.12.5
      helm:
        valueFiles:
          - $values/cluster/helm/alloy/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
