apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 9.7.0
      helm:
        valueFiles:
          - $values/cluster/helm/argocd/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
