apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  source:
    repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
    targetRevision: HEAD
    path: cluster/services
    directory:
      include: cloudflared.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
