apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-only
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.pushover: ""
    notifications.argoproj.io/subscribe.on-health-degraded.pushover: ""
spec:
  project: default
  source:
    repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
    targetRevision: HEAD
    path: cluster/ingress-only
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
