apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-event-exporter
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: kubernetes-events-exporter
      repoURL: ghcr.io/ownkube/charts
      targetRevision: 0.1.2
      helm:
        valueFiles:
          - $values/cluster/helm/kubernetes-event-exporter/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
