apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: loki
      repoURL: ghcr.io/grafana-community/helm-charts
      targetRevision: 6.30.1
      helm:
        valueFiles:
          - $values/cluster/helm/loki/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
