---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.7.2
      helm:
        valueFiles:
          - $values/cluster/helm/longhorn/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
