apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-unknown.pushover: ""
spec:
  project: default
  source:
    repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
    targetRevision: HEAD
    path: cluster/metallb
    directory:
      include: l2-config.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
