apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-mcp-server
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-out-of-sync.pushover: ""
spec:
  project: default
  sources:
    - repoURL: https://github.com/ohthehugemanatee/homenet-documentation.git
      targetRevision: HEAD
      ref: values
    - chart: nextcloud-mcp-server
      repoURL: https://cbcoutinho.github.io/nextcloud-mcp-server
      targetRevision: 0.102.7
      helm:
        releaseName: nextcloud-mcp
        valueFiles:
          - $values/cluster/helm/nextcloud-mcp-server/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
