version: "3.4"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=germany.vertesi.com
      - PEERS=2
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /media/bigdrive/.docker/config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      wireguard:
        ipv4_address: 172.28.0.2

networks:
  wireguard:
    ipam:
      driver: default
      config: 
        - subnet: 172.28.0.0/16
  vlan20:
    driver: macvlan
    driver_opts:
      parent: enp1s0f0.20
    ipam:
      config:
        - subnet: 192.168.1.0/24

