name: ci
on:
  push:
    branches: ['master']
jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Log in to the Container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build the image and push
        run: |
          cd cluster/Dockerfiles/nextcloud && 
          docker buildx build \
          --push \
          --tag ghcr.io/${{ github.actor }}/docker-nextcloud:multiarch \
          --platform linux/arm64,linux/amd64,linux/arm/v7 . 
